version: '3'

services:

  #redis
  redis:
    image: "redis:latest"
    container_name: empdept_redis
    command: redis-server --requirepass redis_pass
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      -empdept-network

  #message queue
  rabbitmq:
    image: rabbitmq:management
    container_name: mq_empdept
    ports:
      - 15673:15672
      - 5673:5672
    restart: always
    #volumes setting
    volumes:
      - .$PWD/mq_data:/var/lib/rabbitmq
    networks:
      -empdept-network


  # db related
  db_empdept:
      #构建mysql镜像
      image: mysql:latest
      container_name: empdept_db # 容器名
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root #root管理员用户密码
      ports:
        - '6606:3306'  #host物理直接映射端口为6606
      volumes:
        #mysql数据库挂载到host物理机目录/e/docker/mysql/data/db
        - "/e/docker/mysql/data/db:/var/lib/mysql"
        #容器的配置目录挂载到host物理机目录/e/docker/mysql/data/conf
        - "/e/docker/mysql/data/conf:/etc/mysql/conf.d"
    networks:
      - empdept-network

  empdept:
    container_name: empdept
    restart: unless-stopped
    image: openjdk:8-jdk-alpine
#    depends_on:
#      - db_empdept
    volumes:
#      - ./spring-data:/usr/share/data
      - ./target/empdept-0.0.1-SNAPSHOT.jar:/empdept/empdept-0.0.1-SNAPSHOT.jar
      - ~/.m2:/root/.m2
    ports:
      - "8087:8087"
    command:
      [java,'-jar',-Dspring.profiles.active=prod,'/empdept/empdept-0.0.1-SNAPSHOT.jar']
    networks:
      - empdept-network


#bridge docker network
networks:
  empdept-network:
    driver: bridge

